provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

allInOne:
  enabled: true
  image:
    repository: jaegertracing/all-in-one
    tag: 1.52.0
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi

storage:
  type: memory

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false

ingester:
  enabled: false

hotrod:
  enabled: false 