kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-labeler-dev
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  - containerPort: 4317  # OTLP gRPC
    hostPort: 4317
    protocol: TCP
  - containerPort: 4318  # OTLP HTTP
    hostPort: 4318
    protocol: TCP
  - containerPort: 9090  # Prometheus
    hostPort: 9090
    protocol: TCP
  - containerPort: 3000  # Grafana
    hostPort: 3000
    protocol: TCP
  - containerPort: 16686 # Jaeger UI
    hostPort: 16686
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        eviction-hard: "nodefs.available<5%,nodefs.inodesFree<5%,imagefs.available<5%"
  extraMounts:
  - hostPath: ${PROJECT_ROOT}/tmp
    containerPath: /var/lib/containerd
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16" 