apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
  namespace: otel-demo
data:
  demo.flagd.json: |
    {
      "flags": {
        "recommendationCache": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "on"
        },
        "productCatalogFailure": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "off"
        }
      }
    } 